version: '3'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/habitsgobackend/bin/migrate up && /habitsgobackend/bin/api" ]

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=habits
      - POSTGRES_USER=habits
      - POSTGRES_PASSWORD=habits
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habits -d habits" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always